server:
  port: 8000

spring:
  application:
    name: microcloud-consumer-8000

eureka:
  client:
    register-with-eureka: false #客户端不注册到eureka，只是进行服务的调用
    service-url:
      defaultZone: http://studyjava:hello@eureka-7001.com:7001/eureka,http://studyjava:hello@eureka-7002.com:7002/eureka,http://studyjava:hello@eureka-7003.com:7003/eureka
