server:
  port: 8101


spring:
  application:
    name: microcloud-provider-company


#  security:
#    user:
#      roles:
#        - USER
#      name: studyjava
#      password: hello


#security:
#  basic:
#    enabled: true
#  sessions: stateless

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://studyjava:hello@eureka-7001.com:7001/eureka,http://studyjava:hello@eureka-7002.com:7002/eureka,http://studyjava:hello@eureka-7003.com:7003/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 90 # 如果心跳超过了5秒的间隔（默认是90秒）
    instance-id: company-8101.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址



info:
  app.name: study-microcloud
  company.name: www.study.cn
  build.artifactId: $project.artifactId$
  build.version: $project.verson$


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

logging:
  level:
    org.springframework.security: debug


