server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study8001?characterEncoding=utf-8&useSSL=true&allowMultiQueries=true
    username: root
    password: password
    type: com.alibaba.druid.pool.DruidDataSource
#  security:
#    user:
#      roles:
#        - USER
#      name: studyjava
#      password: hello


#security:
#  basic:
#    enabled: true
#  sessions: stateless



